%% OMEGA: Script for automatic preprocessing
% 
% 1) Import MEG + Convert to continuous (CTF) + Refine registration
% 2) PSD on sensosrs (pre)
% 3) Notch filter (50Hz and harmonics, also 49 Hz and 88 Hz) + High bandpass (0.3 Hz)
% 4) Detect and remove blinks and cardiac
% 5) PSD on sensosrs (post) *skip for now
%
% Saves Report
%
% This script needs function: create_html_report.m and Omg_check_rename.m
%
% 1 June 2021 (v2)
% Guiomar Niso, 26 May 2016 (v1)
% Guiomar Niso, 6 May 2015 (v0)

clc; clear;

%% ==== PARAMETERS ================================================

% 1) MEG datasets storage
mydirMEG = 'C:\Users\Maria\OneDrive - Universidad Politécnica de Madrid\TFM\Pruebas_sujetos\';
% 2) Dir to save progress report
mydirBST = 'C:\Users\Maria\OneDrive - Universidad Politécnica de Madrid\TFM\Reports';

% OMEGA protocol
omegaProt = 'CAMCAN_BSTdb_v1';

% -------------------------------------------------------------------------

% Frequencies to filter with the noth (power line 50Hz and harmonics, also 49 Hz and 88 Hz)
freqs_notch = [50:50:450, 49, 88];
% Filters
highpass = 0.3;
lowpass = 0; % 0: no filter

% Window length and overlap for PSD Welch method
win_length = 4; % sec
win_overlap = 50; % percentage

% =========================================================================

%% Prepare MEG files

%SubjectNames = {'sub-CC110033'};
%SubjectNames = {'sub-CC110037','sub-CC110045','sub-CC110056'}
%SubjectNames = {'sub-CC110098', 'sub-CC110411','sub-CC120008','sub-CC120065','sub-CC120137','sub-CC120319'};
%SubjectNames = {'sub-CC120469','sub-CC121200','sub-CC610146','sub-CC610210', 'sub-CC610344','sub-CC610496'};
SubjectNames = {'sub-CC610576','sub-CC610653','sub-CC620005','sub-CC620114','sub-CC620314','sub-CC620610'};

for iSubject=1:numel(SubjectNames)
       
%% ==== 1) Import MEG files =======================================

% For Brainstorm
sFiles0 = [];
% Start a new report
bst_report('Start', sFiles0);

% SELECCIONAR SUJETO

% Process: Select file names with tag: SUBJECT NAME
sFilesMEG = bst_process('CallProcess', 'process_select_files_data', ...
    sFiles0, [], ...
    'tag', '', ...
    'subjectname', SubjectNames{iSubject}, ...
    'condition', '');

% Process: Select file names with tag: rest
sFilesR = bst_process('CallProcess', 'process_select_tag', ...
    sFilesMEG, [], ...
    'tag', 'rest', ...
    'search', 1, ... % 1: Filename, 2: Comments
    'select', 1);  % Select only the files with the tag

if isempty(sFilesMEG), return; end

% ** Process: Snapshot: Sensors/MRI registration
bst_process('CallProcess', 'process_snapshot', ...
    sFilesR, [], ...
    'target', 1, ...  % Sensors/MRI registration
    'modality', 1, ...% MEG (All)
    'orient', 1, ...  % left
    'time', 0, ...
    'contact_time', [0, 0.1], ...
    'contact_nimage', 12, ...
    'threshold', 30, ...
    'comment', '');


%% ==== 2) PSD on sensors (before filtering) ======================

% Process: Power spectrum density (Welch)
sFilesPSDpre = bst_process('CallProcess', 'process_psd', ...
    sFilesR, [], ...
    'timewindow', [], ...
    'win_length', win_length, ...
    'win_overlap', win_overlap, ...
    'sensortypes', 'MEG, EEG', ...
    'edit', struct(...
         'Comment', 'Power', ...
         'TimeBands', [], ...
         'Freqs', [], ...
         'ClusterFuncTime', 'none', ...
         'Measure', 'power', ...
         'Output', 'all', ...
         'SaveKernel', 0));

% ** Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', ...
    sFilesPSDpre, [], ...
    'target', 10, ...  % Frequency spectrum
    'modality', 1, ...  % MEG (All)
    'orient', 1, ...  % left
    'time', 0, ...
    'contact_time', [0, 0.1], ...
    'contact_nimage', 12, ...
    'threshold', 30, ...
    'comment', '');


%% ==== 3)  Notch filter + High pass (0.3 Hz) =====================

% Process: Notch filter: 50Hz 100Hz 150Hz 200Hz 250Hz 300Hz 450Hz 400Hz
%                        49Hz 88Hz
sFilesNotch = bst_process('CallProcess', 'process_notch', ...
    sFilesR, [], ...
    'freqlist', freqs_notch, ...
    'sensortypes', 'MEG, EEG', ...
    'read_all', 0); 

% Process: High-pass:0.3Hz
sFilesNotchHigh = bst_process('CallProcess', 'process_bandpass', ...
    sFilesNotch, [], ...
    'highpass', highpass, ...
    'lowpass', lowpass, ...
    'mirror', 1, ...
    'sensortypes', 'MEG, EEG', ...
    'read_all', 0);

% Delete intermediate files (Notch) 
for iRun=1:numel(sFilesNotch)
    % Process: Delete data files
    bst_process('CallProcess', 'process_delete', ...
        sFilesNotch(iRun).FileName, [], ...
        'target', 2);  % Delete conditions
end

%% ==== 4) SSP Detect and remove blinks and cardiac ===============

% ==== SELECT RESTING AND NOISE ====

% Process: Select file names with tag: rest
sFilesRESTING = bst_process('CallProcess', 'process_select_tag', ...
    sFilesNotchHigh, [], ...
    'tag', 'rest', ...
    'search', 1, ...
    'select', 1);  % Select only the files with the tag

% ==== DETECT ====
for iRun=1:numel(sFilesRESTING)
    
    % Read the channel file
    ChannelMat = in_bst_channel(sFilesRESTING(iRun).ChannelFile);

    % Look for ECG channel
    iChannelECG = channel_find(ChannelMat.Channel, 'ECG');

    % Look for EOG channel
    iChannelVEOG = channel_find(ChannelMat.Channel, 'EOG062');

    % Process: Detect heartbeats
    if ~isempty(iChannelECG)
        bst_process('CallProcess', 'process_evt_detect_ecg', ...
            sFilesRESTING(iRun), [], ...
            'channelname', ChannelMat.Channel(iChannelECG).Name, ...
            'timewindow', [], ...
            'eventname', 'cardiac');
    end

    % Process: Detect eye blinks
    if ~isempty(iChannelVEOG)
        bst_process('CallProcess', 'process_evt_detect_eog', ...
            sFilesRESTING(iRun), [], ...
            'channelname', ChannelMat.Channel(iChannelVEOG).Name, ...
            'timewindow', [], ...
            'eventname', 'blink');
    end
end

% ==== REMOVE SIMULTANEOUS ====

% Process: Remove simultaneous
bst_process('CallProcess', 'process_evt_remove_simult', ...
    sFilesRESTING, [], ...
    'remove', 'cardiac', ...
    'target', 'blink', ...
    'dt', 0.25, ...
    'rename', 0);

% ==== SSP (force 1st component) ====

% Process: SSP ECG: cardiac
bst_process('CallProcess', 'process_ssp_ecg', ...
    sFilesRESTING, [], ...
    'eventname', 'cardiac', ...
    'sensortypes', 'MEG', ...
    'usessp', 1, ...
    'select', 1);

% Process: SSP EOG: blink
bst_process('CallProcess', 'process_ssp_eog', ...
    sFilesRESTING, [], ...
    'eventname', 'blink', ...
    'sensortypes', 'MEG', ...
    'usessp', 1, ...
    'select', 1);

% ** Process: Snapshot: SSP projectors
bst_process('CallProcess', 'process_snapshot', ...
    sFilesRESTING, [], ...
    'target', 2, ...  % SSP projectors
    'modality', 1, ...  % MEG (All)
    'orient', 1, ...  % left
    'time', 0, ...
    'contact_time', [0, 0.1], ...
    'contact_nimage', 12, ...
    'threshold', 30, ...
    'comment', '');


%% ==== 5) PSD on sensors (after filtering) ======================

% Process: Power spectrum density (Welch)
sFilesPSDpost = bst_process('CallProcess', 'process_psd', ...
    sFilesRESTING, [], ...
    'timewindow', [], ...
    'win_length', win_length, ...
    'win_overlap', win_overlap, ...
    'sensortypes', 'MEG, EEG', ...
    'edit', struct(...
         'Comment', 'Power', ...
         'TimeBands', [], ...
         'Freqs', [], ...
         'ClusterFuncTime', 'none', ...
         'Measure', 'power', ...
         'Output', 'all', ...
         'SaveKernel', 0));
  
% ** Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', ...
    sFilesPSDpost, [], ...
    'target', 10, ...  % Frequency spectrum
    'modality', 1, ...  % MEG (All)
    'orient', 1, ...  % left
    'time', 0, ...
    'contact_time', [0, 0.1], ...
    'contact_nimage', 12, ...
    'threshold', 30, ...
    'comment', '');


%% SAVE REPORT ====================================================

% Save and display report
ReportFile = bst_report('Save', sFiles0);
bst_report('Open', ReportFile);
bst_report('Export', ReportFile, mydirBST);

end